import {
  SET_ID, CHANGE_NAME, CHANGE_COLOR, UPDATE_DATA, SOCKET_CONNECT, SET_ROLE,
} from './user';

import {
  CHANGE_SIZE, NEXT_MOVE, SET_COORDS, COUNT_BOXES, SET_COUNTER, IS_VICTORY, START_GAME,
  RESTART_GAME, GET_SCORES, SAVE_SCORES, calcL, SET_BOXES, SET_SESSION_ID, SET_MESSAGES,
} from './game';

export {
  SET_ID, CHANGE_NAME, CHANGE_COLOR, UPDATE_DATA, SOCKET_CONNECT, SET_ROLE,
  CHANGE_SIZE, NEXT_MOVE, SET_COORDS, COUNT_BOXES, SET_COUNTER, IS_VICTORY, START_GAME,
  RESTART_GAME, GET_SCORES, SAVE_SCORES, calcL, SET_BOXES, SET_SESSION_ID, SET_MESSAGES,
};
